# Generated by Django 3.2.7 on 2023-09-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='m_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
